name: Python CI

on:
  pull_request: {}
  push:
    branches: ["main"]

env:
  PYTHON_VERSION: "3.12"

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache Hatch dependencies
        uses: actions/cache@b7c1be3642e46bf76d47072db3a4a1c330a8db62 # v3.3.2
        with:
          path: ~/.cache/hatch
          key: ${{ runner.os }}-hatch-${{ hashFiles('**/*.toml') }}

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Initialize Hatch
        uses: ./.github/actions/initialize-hatch

      - name: Run bandit
        run: hatch run bandit-ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@4fe5e9b96fb9e0c318c1b94e23ae36368e3c6c07 # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache Hatch dependencies
        uses: actions/cache@b7c1be3642e46bf76d47072db3a4a1c330a8db62 # v3.3.2
        with:
          path: ~/.cache/hatch
          key: ${{ runner.os }}-hatch-${{ hashFiles('**/*.toml') }}

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Initialize Hatch
        uses: ./.github/actions/initialize-hatch

      - name: Run flake8
        run: hatch run flake8-check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@4fe5e9b96fb9e0c318c1b94e23ae36368e3c6c07 # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache Hatch dependencies
        uses: actions/cache@b7c1be3642e46bf76d47072db3a4a1c330a8db62 # v3.3.2
        with:
          path: ~/.cache/hatch
          key: ${{ runner.os }}-hatch-${{ hashFiles('**/*.toml') }}

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Initialize Hatch
        uses: ./.github/actions/initialize-hatch

      - name: Run isort
        run: hatch run isort-check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@4fe5e9b96fb9e0c318c1b94e23ae36368e3c6c07 # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache Hatch dependencies
        uses: actions/cache@b7c1be3642e46bf76d47072db3a4a1c330a8db62 # v3.3.2
        with:
          path: ~/.cache/hatch
          key: ${{ runner.os }}-hatch-${{ hashFiles('**/*.toml') }}

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Initialize Hatch
        uses: ./.github/actions/initialize-hatch

      - name: Run mypy
        run: hatch run mypy-check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@4fe5e9b96fb9e0c318c1b94e23ae36368e3c6c07 # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache Hatch dependencies
        uses: actions/cache@b7c1be3642e46bf76d47072db3a4a1c330a8db62 # v3.3.2
        with:
          path: ~/.cache/hatch
          key: ${{ runner.os }}-hatch-${{ hashFiles('**/*.toml') }}

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Initialize Hatch
        uses: ./.github/actions/initialize-hatch

      - name: Run renovate
        run: hatch run renovate-check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@4fe5e9b96fb9e0c318c1b94e23ae36368e3c6c07 # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
