version: '3.4'

x-mount-app-and-user-git-config: &mount-app-and-user-git-config
  volumes:
    - ./:/app
    - ~/.gitconfig:/home/columbo/.gitconfig # allow script to commit as user


services:

  # a fully loaded development environment to test new code
  devbox: &devbox
    build:
      dockerfile: ./docker/devbox.dockerfile
      context: .
    image: "columbo/devbox"
    volumes:
      - ./:/app

  # run all the tests and linting locally
  # - black & isort will format code to address issues
  test:
    <<: *devbox
    command: ["hatch", "run", "check"]

  # test the documentation examples to make sure they can be run with Python
  validateDocExamples:
    <<: *devbox
    command: ["hatch", "run", "test-docs-examples"]

  # generate and serve the project documentation locally
  mkdocs: &mkdocs
    <<: *devbox
    entrypoint: "mkdocs"
    ports:
      - "8000:8000"
    command: ["hatch", "run", "docs:serve"]

  mike:
    <<: [*mkdocs, *mount-app-and-user-git-config]
    entrypoint: ["hatch", "run", "docs:mike"]
