site_name: columbo Documentation
repo_url: https://github.com/wayfair-incubator/columbo/
repo_name: wayfair-incubator/columbo
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Usage Guide:
    - Fundamentals: usage-guide/fundamentals.md
    - Interactions: usage-guide/interactions.md
    - Optional Questions & Branching: usage-guide/optional-questions-and-branching.md
    - Validators: usage-guide/validators.md
    - Command Line Interface: usage-guide/command-line.md
  - Reference: api.md
  - Development Guide: development-guide.md
  - Changelog: changelog.md
theme: material
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
plugins:
  - redirects:
      redirect_maps:
        usage-guide.md: usage-guide/fundamentals.md
        CHANGELOG.md: changelog.md
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: "restructured-text"
          rendering:
            heading_level: 3
            show_root_heading: True
            show_source: False
            show_root_full_path: False
  - mkdocstrings_patch_type_aliases

extra_css:
  - css/version-select.css
  - css/mkdocstrings.css
extra_javascript:
  - js/version-select.js
