site_name: columbo Documentation
repo_url: https://github.com/wayfair-incubator/columbo/
repo_name: wayfair-incubator/columbo
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Usage Guide:
    - Fundamentals: usage-guide/fundamentals.md
    - Interactions: usage-guide/interactions.md
    - Optional Questions & Branching: usage-guide/optional-questions-and-branching.md
    - Validators: usage-guide/validators.md
    - Command Line Interface: usage-guide/command-line.md
  - Reference: api.md
  - Changelog: CHANGELOG.md
theme: material
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
plugins:
  - redirects:
      redirect_maps:
        usage-guide.md: usage-guide/fundamentals.md
