[tool.black]
line-length = 88
target_version = ['py36']
exclude = '''
/(
    venv
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''

[tool.mypy]
ignore_missing_imports = true

[tool.isort]
line_length=88
multi_line_output=3
include_trailing_comma=true

[tool.pytest.ini_options]
addopts = "--verbose --cov=columbo --cov-report xml:/tmp/coverage.xml --cov-report term-missing"
python_files = "tests/*.py"

[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"
