[tool.black]
line-length = 88
target_version = ['py36']
exclude = '''
/(
    venv
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''

[tool.isort]
line_length=88
multi_line_output=3
include_trailing_comma=true

[tool.coverage.run]
branch = true
data_file = "/tmp/columbo_coverage"

[tool.coverage.report]
fail_under = 90

[tool.coverage.report.excludeLines]
  pragma= "no cover" # Have to re-enable the standard pragma

[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"
