name: "Initialize Hatch"
description: "Install hatch & create an environment"
inputs:
  environment-name:
    description: "Which environment to create"
    default: "default"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Install hatch"
      run: pip install -r requirements-boostrap.txt
      shell: "bash"
    - name: "Create environment"
      run: "hatch env create ${{ inputs.environment-name }}"
      shell: "bash"