name: Version Bump merged

on:
  pull_request:
    types:
      - "closed"
    branches:
      - "main"

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged &&
        startsWith(github.head_ref, 'bump_version_to_') &&
        startsWith(github.event.pull_request.title, 'Bump version') &&
        contains(github.event.pull_request.title, ' → ')
    environment: Create Release
    steps:
      - name: Get new version
        id: get-new-version
        run: |
          NEW_VERSION=$(echo ${{ github.head_ref }} | cut -d _ -f4 )
          echo "::set-output name=version::$NEW_VERSION"
      - name: Is prerelease?
        id: is-prerelease
        run: |
          IS_PRERELEASE=$([[ "${{ steps.get-new-version.outputs.version }}" == *-[a-z]* ]] && echo true || echo false)
          echo "::set-output name=result::$IS_PRERELEASE"
      - name: Create Release
        # Using full SHA for security
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: ncipollo/release-action@18eadf9c9b0f226f47f164f5373c6a44f0aae169 # tag=v1.11.2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          tag: v${{ steps.get-new-version.outputs.version }}
          name: v${{ steps.get-new-version.outputs.version }} Release
          commit: main
          prerelease: ${{ steps.is-prerelease.outputs.result }}
