name: Publish Release

env:
  PYTHON_VERSION: "3.10"

on:
  release:
    types: [published]

jobs:
  update_docs_for_version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # tag=v4.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          requirements: "true"
          test-requirements: "true"
          docs-requirements: "true"

      - name: Push documentation changes
        uses: ./.github/actions/publish-docs-with-mike
        with:
          new_version: true

  build-and-publish-wheel-to-pypi:
    runs-on: ubuntu-latest
    environment: "Publish Release"
    steps:
      - name: Check out code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # tag=v4.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build wheel
        uses: ./.github/actions/build-dist

        # Using full SHA for security
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@d7edd4c95736a5bc1260d38b5523f5d24338bc25 # v1.5.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
